// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package inject

import (
	"cache"
	"cache/iface"
	"cache/local_cache"
)

// Injectors from wire.go:

func InitApp(maxSum int64) (*cache.App, func(), error) {
	lruCache := local_cache.NewLRUCache(maxSum)
	cacheSrv := iface.NewCacheSrv(lruCache)
	app := cache.NewApp(cacheSrv)
	return app, func() {
	}, nil
}
