// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package inject

import (
	"local-cache"
	"local-cache/iface"
	local_cache2 "local-cache/local_cache"
)

// Injectors from wire.go:

func InitApp(maxSum int64) (*local_cache.App, func(), error) {
	lruCache := local_cache2.NewLRUCache(maxSum)
	cacheSrv := iface.NewCacheSrv(lruCache)
	app := local_cache.NewApp(cacheSrv)
	return app, func() {
	}, nil
}
